// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArCiQv38uBc9JaBxJGRP4C94botX6TAEU',
    appId: '1:870522724218:web:91c8e750a2e61af2dac0c3',
    messagingSenderId: '870522724218',
    projectId: 'focusai-d212a',
    authDomain: 'focusai-d212a.firebaseapp.com',
    storageBucket: 'focusai-d212a.firebasestorage.app',
    measurementId: 'G-EJF4HVBEM1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB6fYOuh1dABjG4ob49WvQeOdY_hi3gQU',
    appId: '1:870522724218:android:9d5b92638ae3929cdac0c3',
    messagingSenderId: '870522724218',
    projectId: 'focusai-d212a',
    storageBucket: 'focusai-d212a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5LHfRJH1tDBuuuPfmnIWWe_oLPpdtvbA',
    appId: '1:870522724218:ios:100a78e7030ab806dac0c3',
    messagingSenderId: '870522724218',
    projectId: 'focusai-d212a',
    storageBucket: 'focusai-d212a.firebasestorage.app',
    iosBundleId: 'com.example.focusAiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5LHfRJH1tDBuuuPfmnIWWe_oLPpdtvbA',
    appId: '1:870522724218:ios:100a78e7030ab806dac0c3',
    messagingSenderId: '870522724218',
    projectId: 'focusai-d212a',
    storageBucket: 'focusai-d212a.firebasestorage.app',
    iosBundleId: 'com.example.focusAiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArCiQv38uBc9JaBxJGRP4C94botX6TAEU',
    appId: '1:870522724218:web:3c8e35d2d910cd15dac0c3',
    messagingSenderId: '870522724218',
    projectId: 'focusai-d212a',
    authDomain: 'focusai-d212a.firebaseapp.com',
    storageBucket: 'focusai-d212a.firebasestorage.app',
    measurementId: 'G-ZEVCMM3BBS',
  );
}
